### ISSUE TITLE
Error: Function calls are not supported in decorators

### ISSUE THREAD

**Issue by michelcve** [digitalascetic/ngx-pica#11]
I get the following error in Angular 7.0.2:

`ERROR in @digitalascetic\ngx-pica\ngx-pica.ts(6,2): Error during template compile of 'NgxPicaModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.`

Only get this in production build (dev build gives me the same warning as in [issue 5](https://github.com/digitalascetic/ngx-pica/issues/5).

@edezacas It's stopping us from making a new production build, so I hope you can look into this. Thanks.

**Comment by edezacas** [comment]
This issue must be resolved.
