### ISSUE TITLE
ERROR while compiling

### ISSUE THREAD

**Issue by ShawnRG** [digitalascetic/ngx-pica#16]
Trying to use your library with angular 6:
`ERROR in node_modules/ngx-pica/src/ngx-pica.service.d.ts(1,10): error TS2305: Module '".../node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.`

Don't know if its an issue on my side

**Comment by edezacas** [comment]
@ShawnRG rxjs incompatible version. try to update to angular 7 with long term support

**Comment by zombaki** [comment]
Hi,
I have my rsjs version is @6.5.2 still getting the same build error
ERROR in node_modules/@digitalascetic/ngx-pica/src/ngx-pica.service.d.ts(1,10): error TS2305: Module '"node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
