### ISSUE TITLE
IE polyfill error

### ISSUE THREAD

**Issue by ausshadu** [digitalascetic/ngx-pica#18]
Tested and works correctly on Google Chrome, but on IE this is the error

`SCRIPT1003: Expected ':'`

```
const DEFAULT_PICA_OPTS = {
  tile: 1024,
  concurrency,
  features: [ 'js', 'wasm', 'ww' ],
  idle: 2000
};
```

@edezacas @cbonillah

**Comment by edezacas** [comment]
I'm sorry but aren't in our goals to test this library on IE, so we close and if someone can do a pull request will be welcome.

**Comment by robdmoore** [comment]
FYI This (os a similar syntax error problem) also seems to affect Microsoft Edge, which is a modern browser with significant usage %.
