### ISSUE TITLE
pica demo page is quick but ngx-pica is slow?

### ISSUE THREAD

**Issue by pipoa** [digitalascetic/ngx-pica#19]
I used photos which width/height/size is  3024x4032 , ~2MB
to resize to 800x800, and codes are below
>     
    let dt1 = Date.now();
    const files = event.target.files;
    this._ngxPicaService.resizeImage(files[0], 800, 800).subscribe((imageResized: File) => {
      let reader: FileReader = new FileReader();
      console.log("step1 = " + (Date.now() - dt1) / 1000 + "seconds");
      reader.addEventListener('load', (event: any) => {
        // this.images.push(event.target.result);
        this.image = event.target.result;
        console.log("step2 = " + (Date.now() - dt1) / 1000 + "seconds");
      }, false);
      reader.readAsDataURL(imageResized);
    }, (err) => {
      console.error(err);
    });

Result: 
step1 = **4.785seconds**
step2 = **4.789seconds**

It tooks 4.7~5.5 seconds for resizing. 
However, I try pica demo page [here](http://nodeca.github.io/pica/demo/), it just **3xxms**

Is there any thing I am doing wrong? Or ?
Thanks for helps 

[environment info]
@digitalascetic/ngx-pica@7.0.3
angular7

**Comment by JulianBerger** [comment]
Did you figure out, why it is so slow?

**Comment by edezacas** [comment]
Hi @JulianBerger our library apply by default an image rotation from exif orientation info, taking some time. We've just released a new version improving this feature, now for resize or compress methods we've the possibility to set exifOptions.forceExifOrientation to false, to avoid rotate image and waste some time.

**Comment by JulianBerger** [comment]
Alright, I will test it without the exif readout, thank you! :)

**Comment by wartab** [comment]
> 
> 
> Hi @JulianBerger our library apply by default an image rotation from exif orientation info, taking some time. We've just released a new version improving this feature, now for resize or compress methods we've the possibility to set exifOptions.forceExifOrientation to false, to avoid rotate image and waste some time.

I don't know if it's intended, but the typings make it not just a possibility, but it's mandatory to define it:
```typescript
export interface NgxPicaResizeOptionsInterface {
    exifOptions: ExifOptions;
    aspectRatio?: AspectRatioOptions;
    quality?: number;
    alpha?: boolean;
    unsharpAmount?: number;
    unsharpRadius?: number;
    unsharpThreshold?: number;
}
```

**Comment by edezacas** [comment]
@wartab By default options (NgxPicaResizeOptionsInterface) exifOptions is forced to true. If you want to override this property, you must define as false. But options as method doc is defined, is an optional parameter.

**Comment by wartab** [comment]
No, the option is mandatory as per the typings copied from the repo's code. exifOptions is missing the question mark to make it optional.

**Comment by edezacas** [comment]
@wartab Yes exifOptions is required, because internally we need use it. But options as NgxPicaResizeOptionsInterface is an optional parameter, if you don't set, internally we create a options object with exifOptions.forceExifOrientation set to true. So you haven't to set options parameter if you want to apply exif orientation, otherwise, you need to pass an options parameter with exifOptions.forceExifOrientation set to false.
