### ISSUE TITLE
Angular 8

### ISSUE THREAD

**Issue by bageren** [digitalascetic/ngx-pica#20]
Will this be available for Angular 8? Currently not working for me. Getting this error:

```
./node_modules/ngx-pica/src/ngx-pica.service.js
Module not found: Error: Can't resolve 'rxjs/Subject' in 'C:\Users\Jesper\intergun\node_modules\ngx-pica\src'
```

**Comment by d-mance** [comment]
When you do a npm install it gives you this error. You can fix it only by modifying its imports. Weird thing because when you see the source code it is ok.

**Comment by edezacas** [comment]
We do the update as soon as possible.
