### ISSUE TITLE
Upload new build to npm

### ISSUE THREAD

**Issue by d-mance** [digitalascetic/ngx-pica#21]
Hello,

Thanks for your job, I've just got the ngx-pica from npm public repo but it is not update with the current version in github.

Can you please upload new version to npm?

Thanks in advance and thanks for your job

**Comment by edezacas** [comment]
Npm and github have the same version 7.0.3.

If you have some problem you can try to install the latest version:

npm install @digitalascetic/ngx-pica@7.0.3

**Comment by d-mance** [comment]
Can you try to use it in an angular 8 project?

It is not working fine and I do not know how to explain it.

**Comment by edezacas** [comment]
At this moment it’s not compatible with angular 8. We’ll update as soon as possible.

**Comment by d-mance** [comment]
OK, thanks!
