### ISSUE TITLE
Angular 8.1 Compatibility

### ISSUE THREAD

**Issue by juaal12** [digitalascetic/ngx-pica#22]
Good Afternoon,

I was trying to use this module on angular 8.1 but I realised if does not work at the moment when I tried to launch my application. This module solves what I need to do when it comes to an image resize.
Are you planning on solving this compatibility issue??

Thanks in advance!

**Comment by edezacas** [comment]
Of course, we do as soon as possible.

**Comment by roncromberge** [comment]
Same problem.

Work around: Change in package.json "@angular-devkit/build-angular": to "~0.800.0" And it wil work.

**Comment by edezacas** [comment]
Updated for angular 8.2.2 compatilibity
