### ISSUE TITLE
Module not found: Error: Can't resolve 'exif-js', 'pica'

### ISSUE THREAD

**Issue by luckyboykg** [digitalascetic/ngx-pica#24]
Good evening,
When I install the latest version from ngx-pica and run this cmd in my project: `ng serve` and I see these issues:

> ERROR in ./node_modules/@digitalascetic/ngx-pica/fesm5/digitalascetic-ngx-pica.js
Module not found: Error: Can't resolve 'exif-js' in '\node_modules\@digitalascetic\ngx-pica\fesm5'
ERROR in ./node_modules/@digitalascetic/ngx-pica/fesm5/digitalascetic-ngx-pica.js
Module not found: Error: Can't resolve 'pica' in '\node_modules\@digitalascetic\ngx-pica\fesm5'

Do you have any ideas for this case?

**Comment by luckyboykg** [comment]
I found the answer:
Just install these libraries before install ngx-pica.

`npm install pica --save`
`npm install exif-js --save`

**Comment by edezacas** [comment]
Pica and exif-js are defined as peerDependencies, so you must install both packages. I’m going to update Readme to clarify this step.

**Comment by marcelvarela** [comment]
> Pica and exif-js are defined as peerDependencies, so you must install both packages. I’m going to update Readme to clarify this step.

The Readme has not yet been updated.
I had the same problem.
