### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by voegtlel** [digitalascetic/ngx-pica#25]
Hi there!

It'd be great if there was proper error handling in case the image could not be loaded. As of now, this is silently ignored.

Suggestion: Add
```ts
img.onerror = (err) => {
    resizedImage.error({err: NgxPicaErrorType.READ_ERROR, file: file, original_error: err}):
};
```
to [ngx-pica.service.ts:72](https://github.com/digitalascetic/ngx-pica/blob/d6f5e1d824672145d38eeb3fceb9b308ea7decb8/projects/digitalascetic/ngx-pica/src/lib/ngx-pica.service.ts#L72).

Thanks!

**Comment by edezacas** [comment]
@voegtlel We' ve released 8.0.2 version with your suggestion. Thanks!
