### ISSUE TITLE
When doing resizeImage stuck the browser

### ISSUE THREAD

**Issue by jihin** [digitalascetic/ngx-pica#27]
When doing resizeImage on 3 mb image it stuck the browser. Scrolls not working. Browser Hanging til resize finish.

**Comment by edezacas** [comment]
@jihin Can you give us more information about it? What is your Angular and digitalascetic/ngx-pica version?

Can you paste your code here?

Thanks!

**Comment by edezacas** [comment]
Without info, we can't resolve. Close.
