### ISSUE TITLE
resizeImage not responding when on mobile or tablet

### ISSUE THREAD

**Issue by NiekvR** [digitalascetic/ngx-pica#28]
Hi,

I have a strange problem with your library. When I build a new angular app with just the dependency on your library (and pica / exif-js of course) the resizeImage method works fine on desktop, but on mobile or tablet it just doesnt react. I'm not getting a File or an error in return. See the following link for an example: [https://into-my-garden.firebaseapp.com/](https://into-my-garden.firebaseapp.com/).

Strange thing is: I wanted to create a stackblitz example for you, but strangly using their framework everything works fine: [https://stackblitz.com/edit/angular-tbi1tw?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/angular-tbi1tw?file=src%2Fapp%2Fapp.component.html)

Based on this I figured it might be a dependency problem (stackblitz using different versions of the angular libraries) and experimented with this, but I could not get it working, except when I downgraded the application to angular 7. Since downgrading isn't an option and the app also state it needs an angular version higher then 8.2.2 this is not the solution.

Here the package.json I use for the firebaseapp:

> {
"name": "img", 
"version": "0.0.0",
"scripts": {
"ng": "ng",
"start": "ng serve --port 4300",
"build": "ng build",
"test": "ng test",
"lint": "ng lint",
"e2e": "ng e2e"
},
"private": true,
"dependencies": {
"@angular/animations": "~8.2.14",
"@angular/common": "~8.2.14",
"@angular/compiler": "~8.2.14",
"@angular/core": "~8.2.3",
"@angular/forms": "~8.2.14",
"@angular/platform-browser": "~8.2.14",
"@angular/platform-browser-dynamic": "~8.2.14",
"@angular/router": "~8.2.14\n",
"@digitalascetic/ngx-pica": "^8.0.2",
"exif-js": "^2.3.0",
"pica": "^5.1.0",
"rxjs": "~6.4.0",
"tslib": "^1.10.0",
"zone.js": "~0.9.1"
},
"devDependencies": {
"@angular-devkit/build-angular": "~0.803.19",
"@angular/cli": "~8.3.19",
"@angular/compiler-cli": "~8.2.14",
"@angular/language-service": "~8.2.14",
"@types/node": "~8.9.4",
"@types/jasmine": "~3.3.8",
"@types/jasminewd2": "~2.0.3",
"codelyzer": "^5.0.0",
"jasmine-core": "~3.4.0",
"jasmine-spec-reporter": "~4.2.1",
"karma": "~4.1.0",
"karma-chrome-launcher": "~2.2.0",
"karma-coverage-istanbul-reporter": "~2.0.1",
"karma-jasmine": "~2.0.1",
"karma-jasmine-html-reporter": "^1.4.0",
"protractor": "~5.4.0",
"ts-node": "~7.0.0",
"tslint": "~5.15.0",
"typescript": "~3.5.3"
}
} 

In all other files the apps are similar. You know your library better than I do: do you have suggestions how to fix this?

Kind regards Niek

**Comment by edezacas** [comment]
Hi, @NiekvR we have just released version 8.0.3 which replaces exifjs with exifr. I think this solve your poblem.
