### ISSUE TITLE
'SCRIPT1002: Syntax error' on IE

### ISSUE THREAD

**Issue by ghost** [digitalascetic/ngx-pica#29]
SCRIPT1002 Error occurs in IE.

Is there a solution?

**Comment by xjlin0** [comment]
Somehow, polyfill on Angular 8 cannot convert ngx-pica 1.1.8 to be able to run on IE11, such as back-ticks in Template literals, short hand object properties, etc.  All other libraries converted smoothly.  Really appreciate if anyone suggest anything. thanks!

**Comment by edezacas** [comment]
I'm sorry but aren't in our goals to test this library on IE, so we close and if someone can do a pull request will be welcome.
