### ISSUE TITLE
Microsoft Edge not supported in new version

### ISSUE THREAD

**Issue by EvrenKayali** [digitalascetic/ngx-pica#32]
Hello,
I am having an issue when I use your lib with MS Edge. Do you have a solution for this?

**Problem**
Version 8 and above cause failing of Angular app on MS Edge Browser with syntax error 
SCRIPT5022: SCRIPT5022: Syntax error

![image](https://user-images.githubusercontent.com/21952173/81567015-0b9c3c80-93df-11ea-9b25-071fc68bc49e.png)

**For Reproduce:**
- Create a new angular app.
- Add ngx-pica module as in readme.md file
- Open the Angular app in MS Edge

**Comment by Asher24** [comment]
It is probably a regression from commit b28ca2fa8a1a126f749b2e858640a24e42e7ba17 Mar. 9 2020, changing from exifjs to exifr

**Comment by EvrenKayali** [comment]
Yes @Asher24 , I am pretty sure that is the reason. But  I couldn't solve the problem by using exifr polyfills. We decided to move on server side image resizing.

**Comment by edezacas** [comment]
@EvrenKayali @Asher24 Can you give us a more detailed debug? We've just released a new version forcing to update exifr and pica libraries to last releases. Also we've replaced window.URL.createObjectURL by FileReader API. This may fix this error.
