### ISSUE TITLE
window.URL.createObjectURL not found

### ISSUE THREAD

**Issue by pdemilly** [digitalascetic/ngx-pica#33]
From what I am reading this method and revokeObjectUrl are deprecated.

**Comment by pdemilly** [comment]
In my environment (ionic v3) it fails on that method but after more debugging it seems that this method is indeed defined on window.URL. so must be something else. sorry for the noise

**Comment by pdemilly** [comment]
This is the message I receive in my ionic v3 app based on angular 8

TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided. According to this stackoverflow this function is deprecated since chrome 71

https://stackoverflow.com/questions/53626318/chrome-update-failed-to-execute-createobjecturl-on-url which is confirmed by google chrome status

https://chromestatus.com/features/#createObjectUrl

I will try to produce a PR for it

Thanks

**Comment by edezacas** [comment]
@pdemilly We've just released a new version 8.0.5 or 9.0.1 (depending on your angular version) replacing window.URL.createObjectURL by FileReader API.
