### ISSUE TITLE
The Observable returned by resizeImage() function is never completed

### ISSUE THREAD

**Issue by marcelvarela** [digitalascetic/ngx-pica#37]
In my project, I need to resize an image to two different sizes and I need the result of both to then upload it to the server.

So I used **forkjoin()** from rxjs.
`...`
`let image = evt.target.files[0];`
`let options: NgxPicaResizeOptionsInterface = {
      aspectRatio: {
        keepAspectRatio: true,
        forceMinDimensions: false
      },
      exifOptions: {
        forceExifOrientation: false
      }
    }`

`forkJoin([this.ngxPicaService.resizeImage(image,320, 320, options), this.ngxPicaService.resizeImage(image,720, 720, options)])`
`.subscribe(resizedImages => console.log(resizedImages ))`

But that didn't work, I didn't get any results, because forkJoin will wait for all passed observables to complete and then it will emit an array or an object with last values from corresponding observables.

So I looked into **resizeImage() source code**, and **there the resizedImage observable is never `.complete()`** even when the image is successfully resized, **unlike resizeImages function which in fact does that.**

[https://github.com/digitalascetic/ngx-pica/blob/7b1e93c1f0aa912b8132667573bccbb90b6b9938/projects/digitalascetic/ngx-pica/src/lib/ngx-pica.service.ts](url)

My solution was to use combineLatest instead of forkjoin, because it does not need to wait to the completion of observables.

**But I think the no completion of resizeImage() observable is not good and should be fixed.**

**Comment by edezacas** [comment]
Hi @MVDeveloper1 I'm totally agree with you. We'll try to fix as soon as possible.

**Comment by edezacas** [comment]
Fixed at v.10.0.1.
