### ISSUE TITLE
ERROR in The target entry-point "@digitalascetic/ngx-pica" has missing dependencies:

### ISSUE THREAD

**Issue by leongrin** [digitalascetic/ngx-pica#38]
When I am running my Angular 9 app, I am getting this error.

ERROR in The target entry-point "@digitalascetic/ngx-pica" has missing dependencies:
 - exifr
 - pica

**Comment by edezacas** [comment]
Hi @leongrin both exifr and pica are declared as peerDependencies, so you need to install manually. I'll update Readme to do clarify.
