### ISSUE TITLE
Syntax error in Internet Explorer

### ISSUE THREAD

**Issue by Rockstar311** [digitalascetic/ngx-pica#41]
After import NgxPicaModule in AppModule and use in tsconfig "target": "es5" to serve in IE

![image](https://user-images.githubusercontent.com/22843347/91436064-0d93e980-e870-11ea-9f5c-1033032472ba.png)

I get an Error 
![image](https://user-images.githubusercontent.com/22843347/91436182-4633c300-e870-11ea-9369-043b21d489f8.png)
error redirect us to line with arrow function (arrow function not supported in IE)

![image](https://user-images.githubusercontent.com/22843347/91436332-93179980-e870-11ea-8f1e-3b7a24e7af9f.png)

**Comment by Suave-Universal** [comment]
Facing same issue while loading my code in Edge browser

**Comment by chmop** [comment]
Same issue here
The arrow function comes from exifr
I think es5 builds should import the legacy version of exifr

**Comment by edezacas** [comment]
We've released a new version 10.1.0 updating exifr dependency to the last version 6.0.0. This may be fix this issue. Otherwise you can open a issue to https://github.com/MikeKovarik/exifr/issues
