### ISSUE TITLE
Can't resolve 'exifr' in 'node_modules\@digitalascetic\ngx-pica\fesm5'

### ISSUE THREAD

**Issue by dabasejumper** [digitalascetic/ngx-pica#42]
I'm getting a compiler error with Angular 8

"@digitalascetic/ngx-pica": "^10.0.1",
"exif-js": "^2.3.0",
"pica": "6.1.1",

I've been googling this but haven't come across anything... Any ideas?

**Comment by edezacas** [comment]
@dabasejumper Have you tried install exifr dependecy manually?
`npm i exifr`

**Comment by dabasejumper** [comment]
OMG... really?... I'm sorry to waste your time... I thought it was in exif-js
