### ISSUE TITLE
image corrupted on chrome when resizing

### ISSUE THREAD

**Issue by gregorymaertens** [digitalascetic/ngx-pica#43]
Hello,

the following image is corrupted when using Chrome (Version 86.0.4240.183 (Official Build) (x86_64)). Ok on Safari (Version 14.0 (15610.1.28.1.9, 15610)) and Firefox too (82.0.3 (64-bit)).

![Arte-primitiva-el-1-950x701](https://user-images.githubusercontent.com/1636112/99061152-689cc900-25a1-11eb-8a60-b63f45dc2252.jpg)

Here is a screenshot using the demo app from this project: 
![Screen Shot 2020-11-13 at 11 10 44](https://user-images.githubusercontent.com/1636112/99061405-c7624280-25a1-11eb-96cf-a204dda401bc.png)

While investigating this issue I have noticed that setting alpha: true in the options fixes the issue.
Is it expected? should the default then be true?
Is it a chrome issue? pica bug? using the same picture you can see toggling the alpha value in their demo app (http://nodeca.github.io/pica/demo/) gives the same type of errors (again only in Chrome).

Thanks!

**Comment by edezacas** [comment]
Hi @gregorymaertens You can open an issue to https://github.com/nodeca/pica/issues and clarify.
