### ISSUE TITLE
Package dependency issue

### ISSUE THREAD

**Issue by NektariaMoka** [digitalascetic/ngx-pica#49]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @digitalascetic/ngx-pica@10.1.0
npm ERR! Found: pica@9.0.1
npm ERR! node_modules/pica
npm ERR!   pica@"^9.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer pica@"^6.0.0" from @digitalascetic/ngx-pica@10.1.0
npm ERR! node_modules/@digitalascetic/ngx-pica
npm ERR!   @digitalascetic/ngx-pica@"^10.1.0" from the root project
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

![image](https://user-images.githubusercontent.com/32243109/179364609-e8acbb5e-2aa1-4535-935e-56995dc4fccc.png)

**Comment by edezacas** [comment]
Maked compatibility to angular 14 and pica ^9.0.0 versions
