### ISSUE TITLE
Compiled with warnings - using Angular 6.0.0

### ISSUE THREAD

**Issue by toricctan** [digitalascetic/ngx-pica#5]
Hi, thank you for this great library!  After npm install (npm install @digitalascetic/ngx-pica --save) and ng serve an Angular 6.0.0 project, warnings, as shown below, appear on terminal. 

"WARNING in ../node_modules/@digitalascetic/ngx-pica/node_modules/@angular/core/esm5/core.js
6570:15-36 Critical dependency: the request of a dependency is an expression
WARNING in ../node_modules/@digitalascetic/ngx-pica/node_modules/@angular/core/esm5/core.js
6590:15-102 Critical dependency: the request of a dependency is an expression
ℹ ｢wdm｣: Compiled with warnings." 

Could you please shed some light on this? Thank you.

**Comment by michelcve** [comment]
@edezacas Just a hint, you can probably find the fix for the problem @toricctan is reporting here.

https://github.com/angular/angular/issues/20357

Would be nice if you could fix this warning, thx.

**Comment by edezacas** [comment]
@toricctan @michelcve Related with [digitalascetic/ngx-pica/issues/6](https://github.com/digitalascetic/ngx-pica/issues/6#issuecomment-417307216)

**Comment by TahaDevelop** [comment]
Hello ,

Still having the warning : Critical dependency: the request of a dependency is an expression.
Using Angular-cli and the version 2.0.4 of ngx-pica. 
Some help!

**Comment by aviaur** [comment]
@TahaDevelop I have like you with Angular 6.1.8 and ngx-pica 2.0.4

WARNING in ....../node_modules/@digitalascetic/ngx-pica/node_modules/@angular/core/fesm5/core.js 4982:15-36
Critical dependency: the request of a dependency is an expression

WARNING in ....../node_modules/@digitalascetic/ngx-pica/node_modules/@angular/core/fesm5/core.js 4994:15-102
Critical dependency: the request of a dependency is an expression

**Comment by TahaDevelop** [comment]
I also have a build failed with the AOT :+1: 

ERROR in ../../../@digitalascetic/ngx-pica/ngx-pica.ts(6,2): Error during template compile of 'NgxPicaModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'. :(  :( :(

**Comment by michelcve** [comment]
@edezacas This one creeped up again for me as well. I get the same error as @aviaur with ngx-pica 2.0.4 and Angular 7.0.2
