### ISSUE TITLE
CSP issue from browser-image-compression

### ISSUE THREAD

**Issue by KevinSchiffmann** [digitalascetic/ngx-pica#51]
Hello,

First of all, thank you very much for the library!

Recently, compressorjs has been replaced by browser-image-compression in the 20.x version. Browser-image-compression load by default a worker from a CDN, which cause CSP issue in our project. If i am right, there is an option to disable it (useWebWorker: false):

https://github.com/Donaldcwl/browser-image-compression?tab=readme-ov-file#remarks-on-content-security-policy-csp

If there any way to access this option? Maybe expose it in ngx-pica?

Thank you very much for your help

**Comment by edezacas** [comment]
Hi, we have added a new option useWebWorker to be able to disable the use of web workers by browser-image-compression. You can use updating to @digitalascetic/ngx-pica@20.1.3
