### ISSUE TITLE
Dependency on rxjs-compat in v1.1.8?

### ISSUE THREAD

**Issue by michelcve** [digitalascetic/ngx-pica#6]
The NPM package for v1.1.8 seems to still depend on rxjs-compat. (e.g. ngx-pica.umd.js contains requires for rxjs/Subject, which should be rxjs now, but there are more places).

Viewing your source code, it seems like these dependencies shouldn't have been there. Am I wrong?

And any change you'll be releasing a new version without the dependency for rxjs-compat?

**Comment by edezacas** [comment]
@michelcve We made a mistake with versions when released in npm, so the latest version (compatible with Angular 6) is 2.0.4. 

All 1.x versions are only compatible with Angular 5.

If you upgrade to 2.0.4 version everything should be fine with no dependency issues.

**Comment by michelcve** [comment]
Great, thanks!
