### ISSUE TITLE
Update to Angular 7?

### ISSUE THREAD

**Issue by RichardC64** [digitalascetic/ngx-pica#8]
Because of Angular6 depedency, seems not working with Angular 7.

**Comment by gagandeepbal** [comment]
Any update on this?

**Comment by michelcve** [comment]
@RichardC64 What error did you get? Is it the same as in [issue #5](https://github.com/digitalascetic/ngx-pica/issues/5) ?

**Comment by Pantelispanka** [comment]
WARNING in ./node_modules/@digitalascetic/ngx-pica/node_modules/@angular/core/fesm5/core.js 4994:15-102
Critical dependency: the request of a dependency is an expression


And when building it with aot option breaks with:

ERROR in ../@digitalascetic/ngx-pica/ngx-pica.ts(6,2): Error during template compile of 'NgxPicaModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'.

**Comment by michelcve** [comment]
@Pantelispanka k, same I get in [issue #11](https://github.com/digitalascetic/ngx-pica/issues/11) and  [issue #5](https://github.com/digitalascetic/ngx-pica/issues/5) then. Hope someone will fix it soon :-(.

**Comment by eralvarez** [comment]
Guys just FYI, you shouldn't use ng versions that are not LTS..

**Comment by savilaf** [comment]
The problem is related to this issue

**Comment by savilaf** [comment]
The problem is related to this [#3854](https://github.com/angular/angular-cli/issues/3854). A quick temporary solution is delete _node_modules_ on @digitalascetic/ngx-pica.

**Comment by edezacas** [comment]
We've just launched a new version for LTS compatible with angular 7.

**Comment by RichardC64** [comment]
great. Thank's

**Comment by michelcve** [comment]
@edezacas First of all thanks for the update. It seems however that it is now required to install both 'pica' and 'exif-js' package in my own project. Is this intentional? (seems to be caused by the removal of the package-lock.json ?)

**Comment by WUKS87** [comment]
@edezacas Do you have in plan to update ngx-pica for Angular 9?
